### PR TITLE
Everything *should* be implemented

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
needs more tests though

```
=============================== Coverage summary ===============================
Statements   : 51.99% ( 157/302 )
Branches     : 34.44% ( 83/241 )
Functions    : 90% ( 9/10 )
Lines        : 52.6% ( 152/289 )
================================================================================
```

### CODE REVIEW

**Comment by postatum** [comment]
I've just removed expanded and canonical forms out from `fixtures/types.js`. I've added it to separate fixtures before but forgot to remove it from `types.js`

**Comment by ForsakenHarmony** [comment]
yeah, the comments are only there so I know what's implemented and can quickly check if something is wrong

**Comment by ForsakenHarmony** [comment]
Also this is currently just a merge from my branch into `develop`

**Comment by jstoiko** [comment]
would be nice to have a list of remaining things to do (aka TODOs), otherwise merging this now.

**Pull request merged**
